### Assigning Subsequent Rows to Matrix first row elements

In [3]:
test_list = [[5, 8, 9], [2, 0, 9], [5, 4, 2], [2, 3, 9]]

## test_list = [[5, 8], [2, 0], [5, 4]]

result = {test_list[0][i]:test_list[i+1] for i in range(len(test_list)-1)}

print(result)

{5: [2, 0, 9], 8: [5, 4, 2], 9: [2, 3, 9]}


### Adding and Subtracting Matrices

In [5]:
import numpy as np

A = np.array([[1, 2], [3, 4]])

B = np.array([[4, 5], [6, 7]])

print("matrix A:")
print(A)

print("\nmatrix B:")
print(B)

print("\nAddition of two matrix:")
print(np.add(A,B))

print("\nSubtraction of two matrix:")
print(np.subtract(A,B))

matrix A:
[[1 2]
 [3 4]]

matrix B:
[[4 5]
 [6 7]]

Addition of two matrix:
[[ 5  7]
 [ 9 11]]

Subtraction of two matrix:
[[-3 -3]
 [-3 -3]]


### Group similar elements into Matrix

In [11]:
from itertools import groupby

test_list = [1, 3, 5, 1, 3, 2, 5, 4, 2]

res = [list(val) for key,val in groupby(sorted(test_list))]

print(res)

[[1, 1], [2, 2], [3, 3], [4], [5, 5]]


### Row-wise element Addition in Tuple Matrix

In [12]:
test_list = [[('Gfg', 3), ('is', 3)], [('best', 1)], [('for', 5), ('geeks', 1)]]

cus_eles = [6, 7, 8]

result_list = []

for i, row in enumerate(test_list):
    result_list.append(list(map(lambda x: x+(cus_eles[i],), row)))

print(result_list)

[[('Gfg', 3, 6), ('is', 3, 6)], [('best', 1, 7)], [('for', 5, 8), ('geeks', 1, 8)]]


### Create an n x n square matrix, where all the sub-matrix have the sum of opposite corner elements as even

In [21]:
def sub_mat(n):
    element=1
    mat=[]
    for i in range(n):
        row=[]
        for j in range(n):
            row.append(element)
            element+=1
        mat.append(row)
    if n%2==0:
        for i in range(n):
            if i%2!=0:
                mat[i][:] = mat[i][::-1]
    for i in range(n):
        for j in range(n):
            print(mat[i][j],end=" ")
        print("\n")
n=4
sub_mat(n)

1 2 3 4 

8 7 6 5 

9 10 11 12 

16 15 14 13 

